INSERT INTO ITEM (ITEM_NUMBER, ITEM_DESCRIPTION) VALUES ('ART_1', 'Eine Kiste Bananen');
INSERT INTO SUB_ITEM (SUB_ITEM_NUMBER, ITEM_ID) VALUES ('SUB_ART_1', 1);
INSERT INTO SUB_ITEM (SUB_ITEM_NUMBER, ITEM_ID) VALUES ('SUB_ART_2', 1);
INSERT INTO SUB_ITEM (SUB_ITEM_NUMBER, ITEM_ID) VALUES ('SUB_ART_3', 1);
INSERT INTO SUB_ITEM (SUB_ITEM_NUMBER, ITEM_ID) VALUES ('SUB_ART_4', 1);
